Repository Rama-Has/Vehicle_Plate_Number_Recognition, pull requests merged in 2023-03, with the labels that each got.

#8 Main Page Frontend
  static/.gitkeep
  static/css/style.css
  static/js/index.js
  templates/.gitkeep
  templates/index.html
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#13 extraction plate number function using vision api
  requirements.txt
  src/utils/__init__.py
  src/utils/visionAPI.py
Labels: enhancement, good first issue

#18 add screenshots
  README.md
Labels: documentation
